### ISSUE TITLE
[TASK] Smoke Tests for RPC Uptime - Lava

### ISSUE THREAD

**Issue by trechriron** [near/Infrastructure-Working-Group#103]
**Summary**

Add unit tests for RPC uptime. Report to new dashboard?

**Details**

**Additional Information**

**Comment by trechriron** [comment]
@jberrytech  - please gather Lava team github usernames and forward to @trechriron (me). I can add them to both the repo and project. You can then assign Lava resources to tickets. Thanks!

**Comment by ewiner** [comment]
Deprioritizing, letting Lava succeed on its own merits.
