### ISSUE TITLE
[DEFECT] Sender Issues 

### ISSUE THREAD

**Issue by Kunrad1987** [near/Infrastructure-Working-Group#31]
Sender issues: 

1. Is slow with refresh balance
2. Ref Finance deposit and withdraw button, sometimes work  and sometimes it doesnt
3. when u use multiple acct with ref, switching between acct, cause a lot of weird issues

**Comment by trechriron** [comment]
@Kunrad1987  - please report these feature requests to Sender directly. Thanks!
