### ISSUE TITLE
[TASK] Choose Chain ID for Aurora Web3 Wallet Project

### ISSUE THREAD

**Issue by trechriron** [near/Infrastructure-Working-Group#40]
**Summary**

**Details**

We will need to choose the Chain ID number by the end of this week.

For the Mainnet Chain ID, the following options are available at [https://chainlist.org/](https://chainlist.org/): 

* 161803 (the Golden Ratio)
* 271828 (Euler's number)
* 145118 (the alphabet number of letters NEAR 14-5-1-18).
* The adjacent numbers of the above are available as well for Testnet options.

It can be any other random and available number (e.g. 131316151-131316153, whereas 131316154 is Aurora Mainnet).

We will choose one of the above if we don't receive any objections or ideas by Friday.

**Additional Information**

**Comment by rasfies** [comment]
The current working idea is to use 397, which is a part of the default HD path for the NEAR Wallet in Ledger (44'/397'/0'/0'/0).
