### ISSUE TITLE
[TASK] Fix nearblocks main page load time

### ISSUE THREAD

**Issue by vikpande** [near/Infrastructure-Working-Group#41]
**Summary**

slow loading/performance - main page (takes 6-8 seconds to load) 

<img width="1050" alt="image" src="https://github.com/near/Infrastructure-Working-Group/assets/15668152/f3a45b93-d1b4-4741-8969-99fccc835f80">

**Details**

main page takes 6-8 seconds to load. Discussed with the team to reduce it to a couple of seconds. 

**Additional Information**

issue was reported by Hot team
some improvements have been made by nearblocks team

**Comment by ewiner** [comment]
Thanks, I'm going to close this ticket but we'll take this as feedback on future milestones/grants for Nearblocks.
