### ISSUE TITLE
[TASK] New RPC Providers

### ISSUE THREAD

**Issue by trechriron** [near/Infrastructure-Working-Group#82]
**Summary**

Pave way for more RPC providers.

**Details**

1. Establish a standardized selection process for RPC providers.
2. Implement and publish standards (via RFP?) to help new providers submit proposals.
3. Devise and publish cost guidelines for new partners to submit against. 

**Additional Information**

**Comment by ewiner** [comment]
IC getting out of the RPC provider game.
