### ISSUE TITLE
[TASK] FASTNEAR - New Routing Strategy

### ISSUE THREAD

**Issue by trechriron** [near/Infrastructure-Working-Group#84]
**Summary**

1. Implement and monitor the new routing strategy.
2. Track performance of FastNEAR's features.

**Details**

1. Implement and monitor the new routing strategy.
2. Track performance of FastNEAR's features.

**Additional Information**

**Comment by ewiner** [comment]
Closing b/c this should be rolled into FastNear's proposals.
