### ISSUE TITLE
[DECISION] Kitwallet + Query API - Sunset Plan?

### ISSUE THREAD

**Issue by trechriron** [near/Infrastructure-Working-Group#9]
**Decision To Be Made -- Summary**
How will we leverage QueryAPI with Kitwallet? What is the sunset plan for Kitwallet?

**Problem**
Kitwallet API is very slow. Uses SQL queries.

**Solutions Considered**
Infra DAO for oversight. DevHub for funding. Find community team to develop?

**Solution Chosen**

**Comment by trechriron** [comment]
Meeting ntoes 2024.2.22
Vik - Interim solution - proxy endpoints. Whole URL. Currently in PROD since MON.
Pending - staking API. Works on some wallets, not on others.
Pavel - indexer to QueryAPI
TODO - Trentin to write RFP for Contract Helper / Kitwallet sunset / replacement (Andy's plan).

**Comment by pkudinov** [comment]
Update on QueryAPI side: we are close to releasing access keys indexer (https://near.org/dev-queryapi.dataplatform.near/widget/QueryApi.App?selectedIndexerPath=eduohe.near/access_keys_v1) and are planning to replace it directly in the contract helper (KitWallet) codebase.

In addition, we have stacking indexer implementation on QueryAPI (https://near.org/dev-queryapi.dataplatform.near/widget/QueryApi.App?selectedIndexerPath=nearpavel.near/staking_v5) as well and after backfilling it we could integrate it with the contract helper (KitWallet) codebase. @eduohe is leading the effort for these.

**Comment by eduohe** [comment]
Both indexers were created in QueryAPI and Kitwallet endpoints migrated
